DROP DATABASE TMS;
CREATE DATABASE IF NOT EXISTS TMS;
USE TMS;

DROP USER IF EXISTS 'tms'@'localhost';
CREATE USER 'tms'@'localhost' IDENTIFIED BY 'tmsPassword*2019';
GRANT SELECT, INSERT, UPDATE, DELETE, DROP ON `tms`.* TO 'tms'@'localhost';

CREATE TABLE IF NOT EXISTS `User` (
	UserID			INT UNSIGNED NOT NULL AUTO_INCREMENT,
	Username		VARCHAR(32) NOT NULL UNIQUE,
    `Password`		VARCHAR(64) NOT NULL,
    Email			VARCHAR(32) NOT NULL,
    FirstName		VARCHAR(32) NOT NULL,
    LastName		VARCHAR(32) NOT NULL,
    UserType		TINYINT DEFAULT 0,
    
    PRIMARY KEY (UserID)
);

CREATE TABLE IF NOT EXISTS Carrier (
	CarrierID		INT UNSIGNED NOT NULL AUTO_INCREMENT,
	Name			VARCHAR(32) NOT NULL,
    DepotCity		VARCHAR(32) NOT NULL,
    FtlAvailability	INT NOT NULL,
    LtlAvailability	INT NOT NULL,
    
    PRIMARY KEY (CarrierID)
);

CREATE TABLE IF NOT EXISTS FTLRate (
	CarrierID	INT UNSIGNED NOT NULL UNIQUE,
    Rate		FLOAT NOT NULL,
    
    PRIMARY KEY (CarrierID),
    FOREIGN KEY (CarrierID) REFERENCES Carrier(CarrierID)
);

CREATE TABLE IF NOT EXISTS LTLRate (
	CarrierID	INT UNSIGNED NOT NULL UNIQUE,
    Rate		FLOAT NOT NULL,
    
    PRIMARY KEY (CarrierID),
    FOREIGN KEY (CarrierID) REFERENCES Carrier(CarrierID)
);

CREATE TABLE IF NOT EXISTS ReeferCharge (
	CarrierID	INT UNSIGNED NOT NULL UNIQUE,
    Charge		FLOAT NOT NULL,
    
    PRIMARY KEY (CarrierID),
    FOREIGN KEY (CarrierID) REFERENCES Carrier(CarrierID)
);

CREATE TABLE IF NOT EXISTS Customer (
	CustomerID		INT UNSIGNED NOT NULL AUTO_INCREMENT,
    CustomerName	VARCHAR(48) NOT NULL,
    
    PRIMARY KEY (CustomerID)
);

CREATE TABLE IF NOT EXISTS Contract (
	ContractID	INT UNSIGNED NOT NULL AUTO_INCREMENT,
    CarrierID	INT UNSIGNED NOT NULL,
    CustomerID	INT UNSIGNED NOT NULL,
    Quantity	INT UNSIGNED NOT NULL,
    LoadType	TINYINT NOT NULL,
    VanType		TINYINT NOT NULL,
    OriginCity	VARCHAR(32) NOT NULL,
    DestCity	VARCHAR(32) NOT NULL,
    
    PRIMARY KEY (ContractID),
    FOREIGN KEY (CustomerID) REFERENCES Customer(CustomerID),
    FOREIGN KEY (CarrierID) REFERENCES Carrier(CarrierID)
);
